In [1]:
import numpy as np
from stl import mesh

In [10]:
# radial, azimuth, longitudinal
# outwards, around, along
# girth, angle, length 
# rho, phi, z

def sc_6_into_magic_ring():
    #for a circle: round, stitch, 0-1
    ring = (0,0,0.5)
    polar_bottom = [(1,0,0),(1,1,0),(1,2,0),(1,3,0),(1,4,0),(1,5,0)]
    polar_top = [(1,0,1),(1,1,1),(1,2,1),(1,3,1),(1,4,1),(1,5,1)]
    vertices = []
    vertices.append(to_cartesian(ring))
    for point in polar_bottom:
        print(point)
        print(to_cartesian(point))
        vertices.append(to_cartesian(point))
    for point in polar_top:
        vertices.append(to_cartesian(point))
    # 0=ring, 1-6=[bottom points] 7-12[top points]
    faces = [[0,1,2],[0,7,8],[1,2,7],[2,7,8],
            [0,2,3],[0,8,9],[2,3,8],[3,8,9],
            [0,3,4],[0,9,10],[3,4,9],[4,9,10],
            [0,4,5],[0,10,11],[4,5,10],[5,10,11],
            [0,5,6],[0,11,12],[5,6,11],[6,11,12],
            [0,6,1],[0,12,7],[6,1,12],[1,12,7]]
    print(vertices)
    return np.array(vertices), np.array(faces)

def to_cartesian(point):
    r = point[0]
    theta = point[1]
    x = r*np.cos(theta)
    y= r*np.sin(theta)
    return (x,y,point[2])

In [11]:
vertices,faces = sc_6_into_magic_ring()


(1, 0, 0)
(1.0, 0.0, 0)
(1, 1, 0)
(0.5403023058681398, 0.8414709848078965, 0)
(1, 2, 0)
(-0.4161468365471424, 0.9092974268256817, 0)
(1, 3, 0)
(-0.9899924966004454, 0.1411200080598672, 0)
(1, 4, 0)
(-0.6536436208636119, -0.7568024953079282, 0)
(1, 5, 0)
(0.28366218546322625, -0.9589242746631385, 0)
[(0.0, 0.0, 0.5), (1.0, 0.0, 0), (0.5403023058681398, 0.8414709848078965, 0), (-0.4161468365471424, 0.9092974268256817, 0), (-0.9899924966004454, 0.1411200080598672, 0), (-0.6536436208636119, -0.7568024953079282, 0), (0.28366218546322625, -0.9589242746631385, 0), (1.0, 0.0, 1), (0.5403023058681398, 0.8414709848078965, 1), (-0.4161468365471424, 0.9092974268256817, 1), (-0.9899924966004454, 0.1411200080598672, 1), (-0.6536436208636119, -0.7568024953079282, 1), (0.28366218546322625, -0.9589242746631385, 1)]


In [12]:
# Create the mesh
circle = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
print(circle)
for i, f in enumerate(faces):
    for j in range(3):
        print(vertices[f[j],:])
        circle.vectors[i][j] = vertices[f[j]]

# Write the mesh to file
circle.save('circle.stl')

[0.  0.  0.5]
[1. 0. 0.]
[0.54030231 0.84147098 0.        ]
[0.  0.  0.5]
[1. 0. 1.]
[0.54030231 0.84147098 1.        ]
[1. 0. 0.]
[0.54030231 0.84147098 0.        ]
[1. 0. 1.]
[0.54030231 0.84147098 0.        ]
[1. 0. 1.]
[0.54030231 0.84147098 1.        ]
[0.  0.  0.5]
[0.54030231 0.84147098 0.        ]
[-0.41614684  0.90929743  0.        ]
[0.  0.  0.5]
[0.54030231 0.84147098 1.        ]
[-0.41614684  0.90929743  1.        ]
[0.54030231 0.84147098 0.        ]
[-0.41614684  0.90929743  0.        ]
[0.54030231 0.84147098 1.        ]
[-0.41614684  0.90929743  0.        ]
[0.54030231 0.84147098 1.        ]
[-0.41614684  0.90929743  1.        ]
[0.  0.  0.5]
[-0.41614684  0.90929743  0.        ]
[-0.9899925   0.14112001  0.        ]
[0.  0.  0.5]
[-0.41614684  0.90929743  1.        ]
[-0.9899925   0.14112001  1.        ]
[-0.41614684  0.90929743  0.        ]
[-0.9899925   0.14112001  0.        ]
[-0.41614684  0.90929743  1.        ]
[-0.9899925   0.14112001  0.        ]
[-0.41614684  0.9